version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - db_mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=graphql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: always

volumes:
  db_mysql:
